// AUTOMATISCH GENERIERT von scripts/generate-article-index.mjs — nicht von Hand bearbeiten.
import type { Article } from "./types";

import a0 from "@/content/articles/assassins-creed-black-flag-resynced-ps5-verkaufszahlen-2026.json";
import a1 from "@/content/articles/baldurs-gate-3-livestream-sperrung-haarlep-2026.json";
import a2 from "@/content/articles/bandai-namco-tgs-2026-lineup.json";
import a3 from "@/content/articles/beast-of-reincarnation-patch-story-pacing-2026.json";
import a4 from "@/content/articles/bergwerk-mining-sim-hindsight-studios-2026.json";
import a5 from "@/content/articles/crimson-moon-release-september-2026.json";
import a6 from "@/content/articles/diablo-4-rebirth-eternal-seasonal-charaktere.json";
import a7 from "@/content/articles/diablo-4-switch-2-port-leak-september-2026.json";
import a8 from "@/content/articles/ea-700-millionen-kostensenkung-2026.json";
import a9 from "@/content/articles/ea-fc-27-the-grounds-nba-2k-vorbild.json";
import a10 from "@/content/articles/ea-massenentlassungen-pif-uebernahme-2026.json";
import a11 from "@/content/articles/electronic-arts-privatisierung-abgeschlossen.json";
import a12 from "@/content/articles/eric-baptizat-assassins-creed-game-director-2026.json";
import a13 from "@/content/articles/fc-27-the-grounds-open-world-modus.json";
import a14 from "@/content/articles/final-fantasy-vii-revelation-spinoffs-verbindung.json";
import a15 from "@/content/articles/fire-emblem-fortunes-weave-direct-details-2026.json";
import a16 from "@/content/articles/fortnite-kingdom-hearts-leak-2026.json";
import a17 from "@/content/articles/gears-of-war-e-day-pvp-versus-early-access-beta.json";
import a18 from "@/content/articles/grafikkarten-preise-asien-speicherkrise-2026.json";
import a19 from "@/content/articles/gta-6-verschiebung-ex-entwickler-mike-york-2026.json";
import a20 from "@/content/articles/halo-campaign-evolved-cod-black-ops-ps5-verkaufszahlen.json";
import a21 from "@/content/articles/halo-campaign-evolved-turbulente-entwicklung.json";
import a22 from "@/content/articles/halo-studios-entlassungen-campaign-evolved-2026.json";
import a23 from "@/content/articles/marvel-rivals-season-9-5-speicherplatz-reduktion.json";
import a24 from "@/content/articles/marvel-rivals-summer-festival-vol-2-2026.json";
import a25 from "@/content/articles/minecraft-switch-2-vibrant-visuals-release.json";
import a26 from "@/content/articles/monster-hunter-wilds-prologue-demo-2026.json";
import a27 from "@/content/articles/project-zomboid-spielerrekord-update-2026.json";
import a28 from "@/content/articles/resident-evil-veronica-remake-2-millionen-wishlists.json";
import a29 from "@/content/articles/sony-disc-aus-2028-david-jaffe-kritik.json";
import a30 from "@/content/articles/sony-tariff-rueckerstattung-ps5-preis-2026.json";
import a31 from "@/content/articles/walking-dead-streets-of-survival-release.json";
import a32 from "@/content/articles/xbox-game-pass-lineup-august-2026.json";
import a33 from "@/content/articles/xbox-helix-abwaertskompatibilitaet-leak-2026.json";
import a34 from "@/content/articles/xbox-platinum-trophy-aequivalent-2026.json";
import a35 from "@/content/articles/xbox-preiserhoehung-europa-2026.json";
import a36 from "@/content/articles/xenoblade-chronicles-2-switch-2-edition-bugs-update.json";

export const ALL_ARTICLES = [a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36] as unknown as Article[];
